name: Deploy to Azure
#comentario
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H 40.76.139.12 >> ~/.ssh/known_hosts

      - name: Pull and restart Apache
        run: |
          ssh -o StrictHostKeyChecking=no jairo@40.76.139.12 << 'EOF'
            cd /var/www/html/app2
            git remote set-url origin git@github.com:jairo06269/Despliegue2.git
            git config --global --add safe.directory /var/www/html/app2
            git pull origin main
            sudo systemctl restart apache2
          EOF
