name: Run Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (ignoring peer deps)
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx
